[package]
name = "rusoto_mock_testcase"
version = "0.1.0"
authors = ["ander <ander.ender@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_s3 = "0.42.0"
rusoto_core = "0.42.0"
rusoto_mock = "0.42.0"
rusoto_credential = "0.42.0"
